(in-package #:schema-protocol/tests)

(deftest json-schema-object
  (defschema %js-addr ()
    (city string))
  (defschema %js-user ()
    (name string :min-length 1)
    (age integer :minimum 0 :optional t)
    (address %js-addr)
    (tags (vector string))
    (:compute label (self)
      (slot-value self 'name))
    (:extra :forbid))
  (let ((js (json-schema '%js-user)))
    (ok (equal "object" (gethash "type" js)))
    (ok (equal "http://json-schema.org/draft-07/schema#" (gethash "$schema" js)))
    (ok (equalp #("name" "address" "tags") (gethash "required" js)))
    (ok (eq nil (gethash "additionalProperties" js)))
    (let ((props (gethash "properties" js)))
      (ok (equal "string" (gethash "type" (gethash "name" props))))
      (ok (= 1 (gethash "minLength" (gethash "name" props))))
      (ok (equal "#/$defs/%js-addr" (gethash "$ref" (gethash "address" props))))
      (ok (eq t (gethash "readOnly" (gethash "label" props)))))
    (ok (hash-table-p (gethash "%js-addr" (gethash "$defs" js))))))

(deftest json-schema-union-enum
  (defschema %js-opt ()
    (color (member :red :blue))
    (note (or :null string) :optional t))
  (let* ((js (json-schema '%js-opt))
         (props (gethash "properties" js)))
    (ok (equalp #(:red :blue) (gethash "enum" (gethash "color" props))))
    (ok (vectorp (gethash "anyOf" (gethash "note" props))))))
